import type { Metadata } from "next";
import { Spline_Sans } from "next/font/google"; 
import {Providers} from "./providers";
import "./globals.css";


// Initialize the Spline Sans font
const splineSans = Spline_Sans({
  subsets: ["latin"],
  variable: "--font-spline-sans",
});

export const metadata: Metadata = {
  title: "Carvana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={splineSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
